from pathlib import Path
p=Path('index.html')
s=p.read_text()
s=s.replace("if(!k)continue,a=by.get(k),chg=", "if(!k)continue;let a=by.get(k),chg=")
s=s.replace('.import{font-size:10px;color:var(--mut);cursor:pointer}', '.top-tools{position:relative;display:flex;align-items:center;gap:10px}.import{font-size:10px;color:var(--mut);cursor:pointer}.import-status{display:flex;align-items:center;gap:6px;font:9px "SFMono-Regular",Consolas,monospace;color:var(--mut);cursor:pointer;user-select:none}.import-status i{width:6px;height:6px;border-radius:50%;background:#a68259}.import-status[data-state="success"] i{background:var(--accent)}.import-status[data-state="error"] i{background:#9b4d3f}.import-status[data-state="reading"] i,.import-status[data-state="importing"] i{animation:impulse 1s infinite alternate}@keyframes impulse{to{opacity:.3}}.import-panel{display:none;position:absolute;right:0;top:25px;width:min(310px,calc(100vw - 32px));padding:14px;background:var(--bg);border:1px solid var(--line);box-shadow:0 12px 34px #19191612;z-index:40;font:9px/1.55 "SFMono-Regular",Consolas,monospace}.import-panel.on{display:block}.import-panel h3{font-size:9px;margin:0 0 10px;padding-bottom:9px;border-bottom:1px solid var(--line);text-transform:uppercase}.import-grid{display:grid;grid-template-columns:62px 1fr;gap:7px 10px}.import-key{color:var(--mut)}.import-detail{margin-top:10px;padding-top:10px;border-top:1px solid var(--line);color:var(--mut);white-space:pre-wrap;overflow-wrap:anywhere}')
old='<header class="top"><a class="brand" href="#today">life/os</a><div><label class="import" for="file">import update</label><input id="file" type="file" accept="application/json,.json" hidden><span id="sync" class="sync"></span></div></header>'
new='<header class="top"><a class="brand" href="#today">life/os</a><div class="top-tools"><label class="import" for="file">import update</label><input id="file" type="file" accept="application/json,.json" hidden><span id="importStatus" class="import-status" data-state="idle"><i></i><span id="importStatusText">no imports</span></span><span id="sync" class="sync"></span><div id="importPanel" class="import-panel"><h3>Import status · <span id="impState">idle</span></h3><div class="import-grid"><span class="import-key">file</span><span id="impFile">—</span><span class="import-key">time</span><span id="impTime">—</span><span class="import-key">storage</span><span id="impMode">—</span><span class="import-key">items</span><span id="impCounts">—</span></div><div id="impDetail" class="import-detail">No import has been attempted yet.</div></div></div></header>'
if old not in s: raise SystemExit('header pattern missing')
s=s.replace(old,new,1)
s=s.replace("if(st.mode==='remote')await S.from('imports').insert({user_id,source_file_name:name,packet:p});else save();render();toast('Life update imported.')", "if(st.mode==='remote'){let ir=await S.from('imports').insert({user_id,source_file_name:name,packet:p});if(ir.error)throw ir.error}else save();render();toast('Life update imported.')")
helpers=r'''const imp=Object.assign({state:'idle',file:'',time:'',mode:'',counts:'',detail:'No import has been attempted yet.'},(()=>{try{return JSON.parse(localStorage.getItem('lifeos.importStatus'))||{}}catch{return{}}})());
function impCounts(p){let n=k=>Array.isArray(p?.[k])?p[k].length:0,c=(p?.coach?.today?1:0)+(p?.coach?.week?1:0)+n('suggestions');return`${n('focus_areas')} areas · ${n('projects')} projects · ${n('tasks')} tasks · ${n('habits')} habits · ${n('evidence')} evidence · ${c} notes`}
function impSet(state,x={}){Object.assign(imp,{state,time:new Date().toISOString(),mode:st.mode,...x});try{localStorage.setItem('lifeos.importStatus',JSON.stringify(imp))}catch{}impRender()}
function impRender(){if(!$('#importStatus'))return;let n={idle:'no imports',reading:'reading…',importing:'importing…',success:'imported',error:'import failed'};$('#importStatus').dataset.state=imp.state;$('#importStatusText').textContent=n[imp.state]||imp.state;$('#impState').textContent=n[imp.state]||imp.state;$('#impFile').textContent=imp.file||'—';$('#impMode').textContent=imp.mode==='remote'?'Supabase cloud':imp.mode==='local'?'this browser':'—';$('#impCounts').textContent=imp.counts||'—';$('#impDetail').textContent=imp.detail||'—';$('#impTime').textContent=imp.time?new Intl.DateTimeFormat('en',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'}).format(new Date(imp.time)):'—'}
function impValidate(p){if(!p||typeof p!=='object'||Array.isArray(p))throw Error('Root must be a LifeOS JSON object.');if(p.version!=null&&Number(p.version)!==1)throw Error(`Unsupported packet version: ${p.version}`);for(let k of['focus_areas','projects','tasks','habits','evidence','suggestions'])if(p[k]!=null&&!Array.isArray(p[k]))throw Error(`${k} must be an array.`);return p}
async function importFile(f){if(!f)return;impSet('reading',{file:f.name,counts:'',detail:'Reading JSON file…'});try{let p;try{p=JSON.parse(await f.text())}catch(e){throw Error(`Invalid JSON: ${e.message}`)}impValidate(p);impSet('importing',{file:f.name,counts:impCounts(p),detail:'Applying LifeOS update…'});await importPacket(p,f.name);impSet('success',{file:f.name,counts:impCounts(p),detail:`Import complete. ${st.mode==='remote'?'Saved to Supabase cloud.':'Saved in this browser.'}`})}catch(e){console.error(e);impSet('error',{file:f.name,detail:e?.message||String(e)});toast('Import failed — open status for details.')}}
'''
pos=s.index('function toast(')
s=s[:pos]+helpers+s[pos:]
old_events="$('#file').addEventListener('change',async e=>{let f=e.target.files?.[0];if(!f)return;try{await importPacket(JSON.parse(await f.text()),f.name)}catch(x){console.error(x);toast('Could not import that update.')}e.target.value=''});"
if old_events not in s: raise SystemExit('file handler pattern missing')
s=s.replace(old_events,"$('#file').addEventListener('change',async e=>{await importFile(e.target.files?.[0]);e.target.value=''});",1)
old_drop="document.addEventListener('drop',async e=>{let f=e.dataTransfer?.files?.[0];if(f)try{await importPacket(JSON.parse(await f.text()),f.name)}catch{toast('Could not import that update.')}});"
if old_drop not in s: raise SystemExit('drop handler pattern missing')
s=s.replace(old_drop,"document.addEventListener('drop',async e=>{await importFile(e.dataTransfer?.files?.[0])});",1)
s=s.replace("let h=e.target.closest('[data-habit]');if(h)habitToggle(h.dataset.habit)});", "let h=e.target.closest('[data-habit]');if(h)habitToggle(h.dataset.habit);let z=e.target.closest('#importStatus');if(z){$('#importPanel').classList.toggle('on');e.stopPropagation()}else if(!e.target.closest('#importPanel'))$('#importPanel').classList.remove('on')});",1)
s=s.replace('(async()=>{view();try{await remote()}', '(async()=>{view();impRender();try{await remote()}',1)
s=s.replace('render()})();', 'render();impRender()})();',1)
p.write_text(s)
